version: 2
jobs:
  build:
    working_directory: ~/circleci-mipqctool-python
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout # checkout source code to working directory
      - run: pip install -r requirements.txt

